### ISSUE TITLE
Incomplete BetMGM endpoint

### ISSUE THREAD

**Issue by atieke27** [the-odds-api/samples-python#2]
Hello,

Just started testing out the API and noticed that not all of the BetMGM spreads are being pulled into the endpoints. For example,
There is a Pittsburgh Steelers game on Sep 11 2022 that has an BetMGM spread as shown here:
<img src="https://user-images.githubusercontent.com/67083821/188792886-24681589-459f-483b-ab08-f185b70d8f17.png" width="600">

But it isn't showing up in the API pull here:

<img src="https://user-images.githubusercontent.com/67083821/188793343-4f9a8d34-9701-49e9-9c8e-0572a3a3a079.png" width="600">

**Comment by the-odds-api** [comment]
Thanks for raising this! We've identified the issue and put through a fix.
